### ISSUE TITLE
Error running install script on sensor node

### ISSUE THREAD

**Issue by strf0x1** [weslambert/securityonion-rita#1]
Ran this on a standalone node and work perfectly. Ran this on a sensor node on a test cluster, and ran into the following error:

```
True
local:
----------
          ID: states
    Function: no.None
      Result: False
     Comment: No Top file or master_tops data matches found. Please see master log for details.
     Changes:
```

It's related to this line in the install script:
```
salt-call state.highstate saltenv=custom queue=
True
```

/opt/custom/salt/top.sls exists, as well as all of the config files.

Thanks for any help/insight you can provide, and thank you for this cool project!
